### ISSUE TITLE
Unit Test Integration

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#14]
The full suite of unit tests are kept in the Canvas repo, but I believe they really belong over here in Easel. However you see fit to integrate our current tests back into the project, go for it @erikgall.

**Comment by austintoddj** [comment]
Right now, @reliq has gotten the `develop` branch functioning properly with the various commands, such as `canvas:update`, which is a HUGE feature. Biggest thing we need to watch out for when re-integrating these unit tests is that we don't break that branch without being able to get it back to where it is now.

**Comment by erikgall** [comment]
@austintoddj So we don't break the `develop` branch, we can create another branch off of that and merge it back in periodically. I'll get on this as soon as I can.. I have a few things I'm wrapping up today/tomorrow for work and should have some time to hop over to canvas stuff on Friday.

**Comment by austintoddj** [comment]
Good thought @erikgall. So far @talvbansal and @reliq have taken a look at the integration, so any help you can lend there would be fantastic. As long as we are all on the same page while we do this, I'm up for being as efficient as possible. And hey, maybe we can all learn something out of this. 👍

**Comment by austintoddj** [comment]
This is not nearly as important as getting the tests integrated back into the project in the first place, but @talvbansal is the speed of the tests being bogged down because the app essentially has to be built/rebuilt in each class?

**Comment by talvbansal** [comment]
The real bottleneck at the moment is that all of the assets need to be "published" in order for the views to be rendered correctly so for every functional test they are being copied again and again on the disk slowing things down substantially. 

 I wrote a comment about a new trait i had to write:
```php
    /**
     * As we use laravel-elixirs "elixir" method in our views
     * PHP will squawk if the versioned files do not exist
     * within the expected directories, this trait will
     * publish assets to the expected location...
     */
```

**Comment by austintoddj** [comment]
Ah yes I saw that. That's a good explanation. And that's something that can be addressed at a later time, or if someone else has any experience in that. But so far you're killin' it! 👍

**Comment by talvbansal** [comment]
Just thinking about this and looking for input, do we think that the integration tests should be a part of the canvas repo since we're testing the whole application being run or think that they're better off remaining here?

**Comment by austintoddj** [comment]
Honestly that was my thought a while ago, but never went anywhere with it @talvbansal. It almost seems like ALL the tests could have been part of the canvas repo, since they all deal with testing the app as a whole. I know that isn't really best practices for TDD or anything, but do you know what I mean?

**Comment by talvbansal** [comment]
I feel like the unit tests belong here but the functional tests belong as part of the main canvas repo. Looking forward to hearing what others think.

**Comment by reliq** [comment]
I agree with this approach.

**Comment by austintoddj** [comment]
Does this add another level of complexity to the the testing integration @talvbansal? Or does it actually simplify it?

**Comment by talvbansal** [comment]
@austintoddj removing the functional tests from Easel has us at another sticking point

Theres a Class called `EloquentTestCase` which is part of the `EloquentPHP` package which contains the following code within:
```php
    /**
     * Get the applications bootstrap file path.
     *
     * @return string
     */
    protected function getBootstrapFilePath()
    {
        return __DIR__.'/../../../../bootstrap/app.php';
    }
```

The `Easel` package the does not have a `bootstrap/app.php` file. 

I've tried looking at some alternatives to get the `bootstrap/app.php` to load using path helpers, but since all the path helpers that laravel ships with `(base_path(), app_path() etc...)` rely on the app container to be created they wont work this early on in the bootstrapping process. 

So I'm not 100% sure how we move forward with the Unit tests now? @erikgall since its your package can you think of anything we could do to make your package usable within other packages?

**Comment by austintoddj** [comment]
After pulling `develop` and running the tests, the first thing that hits me is this:

![screen shot 2016-12-20 at 9 07 25 am](https://cloud.githubusercontent.com/assets/8037011/21355490/d06000e6-c693-11e6-900c-9d4538f1e77a.png)

 Thoughts @talvbansal?

**Comment by talvbansal** [comment]
So the warnings are because we've removed the test annotations from the Model classes. Those won't go away unless we remove the classes.

Not 100% on the login error I'll check it when I get in 😀

**Comment by talvbansal** [comment]
Fixed login issue :)

**Comment by austintoddj** [comment]
What was the fix @talvbansal?

**Comment by austintoddj** [comment]
Alright, great work @talvbansal and @reliq! 

So TravisCI is still throwing this error for the `develop` branch on Canvas, not sure what we could do to fix this. 

<img width="979" alt="screen shot 2016-12-20 at 7 16 14 pm" src="https://cloud.githubusercontent.com/assets/8037011/21374039/3058e24c-c6e9-11e6-96cf-d5fd96e0b8a5.png">

But other than that, we're green on Easel tests. From this point forward, I'd like to adapt a more TDD/BDD approach to Easel, and not have functional tests in there at all. Canvas can retain all the functional stuff, like it does now.

**Comment by reliq** [comment]
Cool.

@talvbansal can we delete the `feature/tests` branch on Easel now?

**Comment by austintoddj** [comment]
Resolved with https://github.com/cnvs/canvas/commit/cb22daa816a1d3de3658370091f567df24a583c9

The problem was that for the TravisCI tests, we never actually ran `php artisan canvas:install`, meaning we never published the assets, config or views.
